### ISSUE TITLE
Terraform crashes on plan

### ISSUE THREAD

**Issue by Prativa20** [vmware-archive/legacy-terraform-provider-vra7#52]
Terraform crashed on plan. Attaching crash log
[crash.log](https://github.com/vmware/terraform-provider-vra7/files/2032330/crash.log)

My main.tf  looks like:

provider  "vra7" {
    username = "<username>"
    password  = "<password>"
    tenant = "<tenant>"
    host = "<host>"
    insecure = true
}

resource "vra7_resource" "example_machine1" {
  catalog_name = "CentOS 6.3"
   resource_configuration = {
         Linux.cpu = "1"
         Windows2008R2SP1.cpu =  "2"
         Windows2012.cpu =  "4"
         Windows2016.cpu =  "2"
     }
     catalog_configuration = {
         lease_days = "5"
     }
     deployment_configuration = {
         reasons      = "I have some"
         description  = "deployment via terraform"
     }
     count = 3
}

**Comment by Prativa20** [comment]
This does not happen when the maps inside resources are empty.
For instance, this crashes the terraform
deployment_configuration = {
reasons = "I have some"
description = "deployment via terraform"
}

BUT the following doesn't
deployment_configuration = {
}

**Comment by virajindasrao** [comment]
Thanks, @Prativa20  for reporting the bug. I will look into it.

**Comment by raghavav** [comment]
Before we dig too deep into this, let me add that I was able to reproduce the issue and then fix it for myself with help from @markpeek.

I don't know why this problem suddenly started happening. But with the following changes, it went away:
1. I downloaded the latest version of golang (1.10.2).
2. I rebuilt the latest Terraform with the new golang.
3. I ran 'dep ensure' in the plugin src directory.
4. I rebuilt the plugin with the new golang.

After that, the crash no longer happened.

Also, the crash happened only when any map in the .tf file had entries. For example, the crash would not happen if the resource_configuration map was empty. If even one map had at least one entry in the .tf file, the crash would occur.

I have asked @Prativa20 to follow my steps above to see if the problem still occurs, but I suspect it won't.

**Comment by raghavav** [comment]
I do run into this bug off and on. I think compiling the plugin without running 'dep ensure' causes the problem. I seem to be able to fix it for myself every time by first running 'dep ensure' before compiling the plugin.

**Comment by Prativa20** [comment]
Running dep ensure before compiling with the latest code and my existing golang version (go1.9.2) works.

**Comment by virajindasrao** [comment]
Closing this bug as the issue has been resolved by 'dep ensure' before compiling the binary.

**Comment by virajindasrao** [comment]
Closing this bug as the issue has been resolved by 'dep ensure' before compiling the binary.

**Comment by widdix123** [comment]
I compiled the  plugin after dep ensure , but the issue still remains . Pleas suggest

**Comment by raghavav** [comment]
Are you trying this with the latest code? Have you correctly installed the compiled plugin?

**Comment by widdix123** [comment]
@raghavav : I followed the steps mentioned here : https://github.com/vmware/terraform-provider-vra7 
The code is latest, built using dep ensure and go build . 

if I add anything inside resource_configuration , i get the below error

**vra7_resource invalid character '<' looking for beginning of value** 

**Code Snippet :**

resource "vra7_resource" "example_machine1" {
  catalog_name = "CentOS 6.3"
   resource_configuration = {
         Linux.cpu = "1"
     }
     catalog_configuration = {
         lease_days = "5"
     }
     deployment_configuration = {
         reasons      = "I have some"
         description  = "deployment via terraform"
     }
     count = 1
}

**Comment by raghavav** [comment]
Ah, this is a completely different issue then, from what I can tell.
Could you turn on debug logging (set TF_LOG environment variable) and send us the output on the screen.
We should be able to tell what is going on.

Thanks

**Comment by Prativa20** [comment]
@widdix123 Also, you should find a vra-terraform.log file in your working space. Please share that as well.

Thanks

**Comment by widdix123** [comment]
@Prativa20 @raghavav 

Here are the details. We tried with Terraform v0.11.8 and we also faced the similar issue using the go and dep version so later switched to Terraform v0.11.9 but still able to produce same error. 

Terraform Version - Terraform v0.11.9-dev
go version - go version go1.11.1 linux/amd64
dep version - version     : v0.5.0
[vRA Terraform log.txt](https://github.com/vmware/terraform-provider-vra7/files/2456172/vRA.Terraform.log.txt)


______________________________
provider "vra7" {
     username = "XXXXXX"
     password = "XXXXX"
     tenant = "XXXXXXXXXX"
     host = "https://XXXXXXXX"
     insecure = "true"
}

resource "vra7_resource" "sample_machine" {
   catalog_name = "Oracle Linux 6.8"
   count = 1
   businessgroup_id = "DevCloud_BG"
   catalog_configuration = {
   lease_days = 14
   }

  resource_configuration = {
    vSphere__vCenter__Machine_1.quota = "group DevCloud_BG"
  }
    deployment_configuration = {
         reasons      = "I have some"
         description  = "deployment via terraform"
     }
}
_____________________________________________________[](url)

**Comment by widdix123** [comment]
@Prativa20 @raghavav Please review the file vRA Terraform log.txt, I save the content of log file to this txt file.

**Comment by widdix123** [comment]
@Prativa20 @raghavav  Any suggestions on what i might be doing wrong here ?

**Comment by Prativa20** [comment]
@widdix123 the file you shared does not have any logs that can be helpful in debugging. There should be a log file called vra-terraform.log, that must have been created inside your working directory. Can you please share that? Also, if you can turn on debug logging (by setting TF_LOG environment variable to DEBUG) and share the console output.

**Comment by widdix123** [comment]
Attached console output.txt file and following is the info from file vra-terraform.log.

[console output.txt](https://github.com/vmware/terraform-provider-vra7/files/2466166/console.output.txt)
2018-10-10T14:20:08.696-05:00 catalog.go:94 readCatalogItemIDByName  INFO 001^[[0m readCatalogItemIdByName->catalog_name Oracle Linux 6.8
2018-10-10T14:20:08.701-05:00 resource.go:232 createResource  INFO 002^[[0m createResource->catalog_id <nil>

Do let me know if any other information is required.

**Comment by Prativa20** [comment]
@widdix123  Can you check if Reconfigure Machine action is turned on in your entitlement?

**Comment by widdix123** [comment]
I do not see that option enabled.

**Comment by Prativa20** [comment]
In that case, this issue is being addressed as part of #73 . Meanwhile, to unblock yourself, try enabling the reconfigure action in your entitlement and it should work.
